### ISSUE TITLE
Wrong ISO Code for Canary Islands  "iso":"ES" 

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/api#243]
**Describe the bug**
Spain and Canary Islands have the same ISO and fiscal_iso
when create a document with iso es you can't specify if is Spain or Canary Island

**To Reproduce**
Create an invoice with es as ISO

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
unfortunately, as you said, the Canary Islands and Spain have the same ISO code.
Please, notice that it is not an issue on its own: the Canary Islands actually have the same [ISO 3166-1](https://it.wikipedia.org/wiki/ISO_3166-1) code.

Even if the ISO code is correct, this creates ambiguities when creating the document using ISO code directly: in the current implementation, our code retrieves the first result of the list, in this case, the Canary Islands.

We're currently looking at the best strategy to overcome this issue, which most probably will be based on the [ISO 3166-2](https://it.wikipedia.org/wiki/ISO_3166-2) standard. The problem is that this standard is used only for territorial subdivisions, so it doesn't exist for the main country and can't replace the ISO 3166-1 value for the subdivisions.

In this case, the Canary Islands will be identified by the couple "ES" for ISO 3166-1 and "ES-CN" for [ISO 3166-2](https://it.wikipedia.org/wiki/ISO_3166-2:ES), while Spain will only have the "ES" for ISO 3166-1.

We'll keep this issue updated when we'll find a feasible solution. 
In the meanwhile, as a temporary workaround, you can use the _country_ field to set up the country as a string for the countries with ambiguities. In this way, you'll be able to set up the country correctly.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
Hello @valmoz ,

We can't find Canary Islands in [ISO 3166-1](https://it.wikipedia.org/wiki/ISO_3166-1), we can find it in [ISO 3166-1 alpha reserved](https://it.wikipedia.org/wiki/ISO_3166-1_alpha-2#Lista_dei_codici_riservati) with different ISO code.

As you suggested in [discussion 222](https://github.com/fattureincloud/api/discussions/222#discussioncomment-4777467)  we switched from "country" to "country_iso" and we changed all our codebase and database.

The FIC api implementation is on our multilanguage platform, so we have to translate (by our side) all the country names that is ok, but you guys have to provide an unique field to create a invoice, right now with the setCountryIso() we are generating invoiced with wrong data because of your implementation, we need to fix this as soon as possible.

Is there any way to use a "uic" filed to create an invoice instead "country" or "country_iso" ?
We suggest also to remove the "set country iso from your sdk", this is not an open source project, we are paying a subscription to use the service and the api.

Thanks 

MM

**Comment by Mattia-Marchiorato** [comment]
Hello @valmoz any news about this?

We are sending electronic invoices with "Canary Island" instead "Spain", we need to fix this as soon as possible.
Please provide a dedline to fix the issue.

Best

MM

**Comment by valmoz** [comment]
Hello @Mattia-Marchiorato,
we'll release the fix on Monday.

I'll keep you updated when it will be live.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
Hello,

ok, thanks

MM

**Comment by valmoz** [comment]
Hello @Mattia-Marchiorato 
the fix was released for this issue. The ISO code for Canary Islands was changed to IC.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
Hello @valmoz 

Ok perfect.

Thanks

MM
